### PR TITLE
Fix views when CAST NULL

### PR DESCRIPTION
**Pull request by ssheikin**
Redshift JDBC driver returns `Invalid VARCHAR length -5` for column type during select from view created as:
```
CREATE VIEW test_view AS SELECT CAST(NULL AS CHARACTER VARYING) AS value
```

According to Postgres documentation:
`atttypmod int4`
atttypmod records type-specific data supplied at table creation time (for example, the maximum length of a varchar column). It is passed to type-specific input functions and length coercion functions. The value will generally be -1 for types that do not need atttypmod.

Seems Redshift JDBC driver uses that in a wrong way - atttypmod is not applicable for null.

## Description

Fix not possible length for varchar.

## Testing

```
CREATE VIEW test_view AS SELECT CAST(NULL AS CHARACTER VARYING) AS value;

select * from test_view;
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [ ] Local run of `mvn install` succeeds
- [ ] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [ ] I have updated the Javadoc documentation accordingly
- [ ] I have read the **README** document
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed
- [ ] A short description of the change has been added to the **CHANGELOG**

## License

- By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ssheikin** [comment]
@bhvkshah @Brooke-white @iggarish @hyandell Could you please take a look on this PR?

**Comment by bhvkshah** [comment]
@ssheikin will have an update for you once I've reviewed your changes. Thank you for the PR!

**Comment by wendigo** [comment]
@bhvkshah any update on that PR?

**Comment by ssheikin** [comment]
Thank you @Brooke-white @bhvkshah for merging! 
When we can expect the new release with the fix?

**Pull request merged**
